### ISSUE TITLE
Power Storage Other Than Accumulator

### ISSUE THREAD

**Issue by Rhyguy1** [mrh0/createaddition#121]
I was wanting to make a power factory, and then I thought, what if I could transport my power via train? Basically, A battery pack that can be used to store mass amounts of power, and can be put on a contraption. This would need some kind of portable power transfer, but it would allow for power to be transferred long distance.

**Comment by mrh0** [comment]
Yes, I've had this thought too, however, I just don't know how I would implement this. Maybe one day I'll do it.

**Comment by McFow1er** [comment]
My suggestion would be to make full-block energy storage blocks with configurable input, output and combo faces either through a GUI interface or through a probably much simpler to do method of using a wrench on the face of the block with contraption connections being managed through an electrical coupling clamp like a high voltage circuit breaker though likely of similar design and function to the fluid transfer coupling blocks where there is no piping or in this cabling in this instance inside the contraption and it is instead managed as an entire object just like fluid tanks and otherwise uses the connectors for power transfer.
Perhaps these battery blocks could even act as scalable multiblocks like tanks too for aesthetic purposes of cramming a bunch together to build up single unit capacity, another possibly could be to make it possibly an upgrade or even a requirement to add an accumulator and using the wrench on it to change between charge, discharge and combo connectors in and out of the multiblock.

I saw this post a week or two ago and figured I'd chime in for possible ideas on the matter as the idea of large scale transportable energy really struck my fancy.

**Comment by Shazuli** [comment]
It would be nice with different types of batteries. If you want one with high energy density it will have high resistance so input and output would be slow. And if you need something that can fill up and drain quickly you have to use one with less density.

There will however only exist a single "battery block" that does nothing, you have to place cells inside of it to have it working. Its these cells that give the battery block its properties (energy density, in-out impedance). A Single battery block could have slots for maybe 2 or 4 cells (maybe even configurable?).

* Redstone Cell (low energy density, low impedance)
* Zinc (derived) Cell (medium energy density, medium impedance)
* Alkaline Cell (high energy density, medium impedance, non-rechargeable)
* Netherite Cell (high energy density, high impedance)

I like the idea of batteries being expensive, which is why the last one would require Netherite.

And lastly; perhaps they will degrade over time. They will lose their max-charge as they are charged and discharged eventually making them worthless forcing you to replace them. But here you can do stuff to keep them healthy, like never discharge them below a certain threshold and stop charging them when they are full. So perhaps a Comparator or some other way of monitoring the charge would allow you to build logic to prevent shorter shelf life of your cells.

**Comment by mrh0** [comment]
Cool ideas, however GUIs, multiblock, and tiered blocks go against the philosophy of Create, though I'm still considering making the movement of energy easier to do

**Comment by Gitcrafter** [comment]
My idea would be a scalable version of the Accumulator, that works and can be expanded like the Item Vault, probably also with a similar maximum-size, with a slightly lower energycapacity and -transferrate per block compared to the regular Accumulator, maybe around 90% or so, energytransfer would be done by switching different faces of the multiblock between: no transfer (neither accepts nor provides energy, the default setting), charging (only accepts energy) and decharging (only provides energy), crafted with a Mechanical Crafter only recipe, similar to the regular Accumulator´s recipe. The Portable Interface would be Brass-tier, crafted with a Brass Casing and a Tesla Coil and would transfer Energy to all regular and Multiblock Accumulators on the connected Contraption, (de-)charging as many Accumulators at once as are required to sustain/absorb the current transferrate, with the maximum-transferrate depending on the total transferrate of all Accumulators on the Contraption

**Comment by mrh0** [comment]
Multiblock accumulator has been added, Energy transport coming soon
