### ISSUE TITLE
Create Crafts & Additions 1.18.1-20220105a has failed to load correctly

### ISSUE THREAD

**Issue by ClaudiusMinimus** [mrh0/createaddition#194]
**Describe the bug**
I am updating my pack, [99 Mods on the Wall](https://www.curseforge.com/minecraft/modpacks/ninety-nine-mods-on-the-wall) and just added Create Crafts & Additions 1.18.1-20220105a. While launching this error shows:

> Create Crafts & Additions (createaddition) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null

![image](https://user-images.githubusercontent.com/17887664/148854917-10962418-d56e-4840-aa03-a8dc699c35ab.png)

**Additional context**
- Mod version: Create Crafts & Additions 1.18.1-20220105a
- Forge version: 39.0.17
- Create version: Create 0.4c

Crash Report
https://crashy.net/IPDNx9N8J4eQ1Sd09dKS
or
https://crashy.net/IPDNx9N8J4eQ1Sd09dKS?raw

**Comment by joxpUB** [comment]
Worth mentioning while there is a new update out due to the new versions of Create/Flywheel, I had the same issue despite installing the new CC&A version through Curseforge (1.18.1-20220110a).

It looks like Curseforge did not remove 1.18.1-20220105a upon update, and furthermore it wanted to "update" 1.18.1-20220110a to 1.18.1-20220105a afterwards.

I resolved this by deleting 1.18.1-20220105a from my mods folder.
