### ISSUE TITLE
Electric Trains?

### ISSUE THREAD

**Issue by ZEROX7** [mrh0/createaddition#301]
just asking if it would be possible to have electric trains with overhead wires so that instead of coal boasting the train it uses RF ?

**Comment by TheStormcrafter** [comment]
I think this is a great Idea, but I think electrification from within the tracks would be better, because you don´t know the height of the trains, because the trains can be build like you want them. Maybe there could also be a upgraded Version, that runs even faster then coal trains, but consumes far more energy.

**Comment by ajh123** [comment]
Maybe have a track with a third rail like the London Underground.

**Comment by TheStormcrafter** [comment]
Sounds great. The London Underground actually uses 4 rails, but that is a really unnecessary detail. You got it on point, what I meant.

**Comment by memetmemet2009hotmailcom** [comment]
> 
yea

**Comment by mrh0** [comment]
Sorry, I'm not adding this
