### ISSUE TITLE
Add buzzing sounds into tesla coil

### ISSUE THREAD

**Issue by Sculktron123** [mrh0/createaddition#307]
Adding buzzing sound in tesla coil make the tesla coil feel more real.

**Comment by mrh0** [comment]
sure, if someone can find a free and unlicensed sound effect for it

**Comment by MR-Spagetty** [comment]
i mean the bee loop sound could work with a pitch of 2, alternatively you could do something similar to what IE did with their breaker switch

**Comment by mrh0** [comment]
tries using the bee sound, didnt sound good :/

**Comment by nightmarishblue** [comment]
I found some audio packs under Creative Commons that could work. [Synthetic Sounds of Electricity](https://freesound.org/people/The-Sacha-Rush/packs/36787/) has some short bursts that could feel right when a player receives a zap. They'd need to be edited first though.

As for continuous drones or buzzes, I have these loops. I'll probably have to search for more.
- [Electric Zap Loop](https://freesound.org/people/Resaural/sounds/531421/)
- [Electric Drill Sound](https://freesound.org/people/davidkyoku/sounds/157730/)

I'm in the process of adding stuff right now and seeing what sounds right. Most free audio recordings are done by hobbyists so they likely won't be as clean as a professional audio library. I'll try to stick to the synthetic stuff to try to avoid that.

Once I'm done I'll probably open a PR but the code is rather poor at the moment. Since Create doesn't expose its soundscape classes publically, I've mostly had to duplicate the code in order to get good, constant ambience out of blocks.
