### ISSUE TITLE
Rolling Mill: Can't use with a hand crank ("Overstressed" / 0 SU) [1.19.2-20221215a]

### ISSUE THREAD

**Issue by exocyt0sis** [mrh0/createaddition#491]
Hi developers.

First off, thank you for an awesome mod! The reason why I started using it was to integrate Mekanism's power generation with Create's machines. Personally, I don't enjoy Create's infinate power sources, so Create Addition's electrical engine fits the bill perfectly!

This being said, I have encounted a possible issue/bug. Crafting an electrical engine requires copper cables, which in turn require the rolling mill. Here's my problem - I can't use the rolling mill with a hand crank. When I do, I get Create's error message "Overstressed". Looking at the rolling mill with the Create Googles reveals that the Rolling Mill generates 0 (zero) SU. For the record, I'm using Minecraft 1.19.2 with Create Addition 20221215a.

Is the "Overstressed" message supposed to show up like that? Also, is there any way around this if I _only_ want to use the crank to power the Rolling Mill?

**Comment by KonSola5** [comment]
A Rolling Mill has an (16x RPM) kinetic stress impact, while Hand Cranks have (8x RPM) kinetic stress capacity. In order to use the Rolling Mill with the Hand Crank, you should halve the speed by placing a large cog on the Rolling Mill, placing a small cog diagonally to a large cog, and placing the Hand Crank on the small cog.

![cogs](https://user-images.githubusercontent.com/125081901/220907993-c87007fb-32b4-47c8-a15a-496c2b85aff9.png)
